### ISSUE TITLE
Gutter option not working

### ISSUE THREAD

**Issue by ajtb** [defunkt/Zen#101]
MacOS Sierra: no matter if the "Gutter" option is checked or not, the line numbers do not disappear. Atom: 1.13.0-beta8

**Comment by linickx** [comment]
👍 OSX 10.11.6 + Atom 1.13.0

**Comment by Turysaz** [comment]
👍

**Comment by mbrav** [comment]
Can confirm, the line numbers do not disappear when the gutter option is checked.

MacOSX 10.12.3, Atom 1.13.1

Thanks to @linickx' for providing a workaround.

**Comment by refactorsaurusrex** [comment]
@defunkt If I submit a PR that resolves this issue, will you accept it?

**Comment by Turysaz** [comment]
@refactorsaurusrex please do! :-)

**Comment by filipgoc** [comment]
I suppose another voice confirming line number keep on showing?

**Comment by refactorsaurusrex** [comment]
Since this repo seems all but abandoned, I'm planning on forking it and releasing an update myself. (Unless someone else beats me to it.) I just haven't had time recently.

**Comment by rm-code** [comment]
@refactorsaurusrex have you tried contacting @braver? IIRC he is the current maintainer.

**Comment by braver** [comment]
Technically I'm the maintainer, but I'm afraid I'm not actively working on it. Don't really have the time. @defunkt seems like a busy guy, so adding maintainers is a bit impractical... but who knows, shoot the guy an email and see what happens.

**Comment by elebumm** [comment]
Are you able to accept pull requests? @braver

**Comment by braver** [comment]
@elebumm definitely can do that. I'm not monitoring this repo, but I could go an do some pr's and a release right now.

**Comment by braver** [comment]
Seems we've got this covered now
