### ISSUE TITLE
Color artifacts in background

### ISSUE THREAD

**Issue by akokai** [defunkt/Zen#103]
There are some strange blocks of non-background color appearing towards the right of the editor display. Looks to be the same as the background color for highlighted text. These regions appear and disappear depending on where the cursor is. Does not look like expected behavior.

![screen shot 2017-03-22 at 12 13 16](https://cloud.githubusercontent.com/assets/1865637/24216373/35474106-0ef9-11e7-9081-c92df498bf6b.png)

Also just noticed that the column between the line numbers and col 0 of text is the same non-background color.

This is Atom 1.15.0 on macOS with default themes for editor & syntax. The only thing I changed for Zen was the width (100 rather than 80 chars).

**Comment by braver** [comment]
I can't reproduce this at all. If anyone finds reliable steps to reproduce, or even better a solution, let me know.
