### ISSUE TITLE
Trigger Zen mode on Atom start up

### ISSUE THREAD

**Issue by kasparsd** [defunkt/Zen#17]
Looks like this repo doesn't have a public Wiki, so I am posting it here. If you want to load Zen mode automatically every time you start Atom, here is a snippet for the `init.coffee`:

```
# Load Zen mode on startup
atom.workspaceView.eachEditorView (editorView) ->
    atom.workspaceView.trigger 'zen:toggle';
```

I am waiting for `eachEditorView` to avoid skewed UI with grey background. There should be a more elegant way of doing this, I guess.

**Comment by jancborchardt** [comment]
Now that the package is further along, how about having this »Start Atom in Zen mode« as a package setting to make it more accessible? @braver

**Comment by jancborchardt** [comment]
The command seems to be outdated:

> Failed to load /home/jan/.atom/init.coffee
> Cannot read property 'eachEditorView' of undefined

What would be the new command?
