### ISSUE TITLE
[Shadow-DOM] grey background when toggling zen with shadow-dom enabled

### ISSUE THREAD

**Issue by nylki** [defunkt/Zen#37]
Hi there,
I noticed that having the new Shadow-DOM support enabled in Atoms settings and toggling the Zen mode, with all themes including the default ones, the Editor displays a grey background/border around the typing space.
Might be related to: https://github.com/defunkt/Zen/issues/22 ?
![bildschirmfoto von 2014-11-21 22 02 24](https://cloud.githubusercontent.com/assets/1710598/5149565/4c6f14e0-71ca-11e4-87fc-504ebc5066b6.png)

**Comment by nylki** [comment]
If anybody is interested, I am using the fork (https://github.com/braver/distraction-free-mode ) by @braver where this issue is fixed.

**Comment by braver** [comment]
@nylki thanks!
