### ISSUE TITLE
Line numbers in zen mode after  Atom update

### ISSUE THREAD

**Issue by alanguir** [defunkt/Zen#43]
It looks like atom was updated, and now line numbers and a background color are visible in zen mode (see screenshot)

Zen 0.10.0
Atom 0.169.0

![screen shot 2015-01-11 at 6 41 30 pm](https://cloud.githubusercontent.com/assets/1456258/5697536/98b3d07e-99c1-11e4-9eac-15a89c7029ee.png)

**Comment by alanguir** [comment]
Update - this is fixed when "use shadow dom" is toggled off in settings.

**Comment by claman** [comment]
The one problem with that solution is that apparently that option is eventually going to be hidden.

**Comment by adius** [comment]
+1

**Comment by chloerei** [comment]
+1

**Comment by braver** [comment]
You could try my fork [distraction-free-mode](https://atom.io/packages/distraction-free-mode), should be solved there.

**Comment by claman** [comment]
Thanks!

**Comment by braver** [comment]
We pulled my fork back into Zen and the latest release also fixes this. I'll be deprecating [distraction-free-mode](https://atom.io/packages/distraction-free-mode) in favour of maintaining this package, so you can switch back to 0.11 and enjoy your moments of Zen.
