### ISSUE TITLE
Few deprecated selectors needs to be changed!

### ISSUE THREAD

**Issue by samarpanda** [defunkt/Zen#48]
### keymaps/zen.cson

- Use the `atom-workspace` tag instead of the `workspace` class.
- Use the `atom-text-editor` tag instead of the `editor` class.

### stylesheets/zen.less

- Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by jasonmelgoza** [comment]
+1

**Comment by braver** [comment]
@samarpanda @jasonmelgoza I've forked this package to [distraction-free-mode](https://atom.io/packages/distraction-free-mode), to solve this and several other issues. Would love to hear what you  guys think.

**Comment by jasonmelgoza** [comment]
@braver - works for me. Thanks!!

**Comment by samarpanda** [comment]
@braver :+1:  Works for me too, Thanks.

**Comment by samarpanda** [comment]
@braver I was wondering if there is a shortcut to switch to code view( without tree structure ) and not  fullscreen?

**Comment by braver** [comment]
@samarpanda @jasonmelgoza Hey guys, we pulled my fork back into Zen and the latest release also fixes this. I'll be deprecating [distraction-free-mode](https://atom.io/packages/distraction-free-mode) in favour of maintaining Zen.

> I was wondering if there is a shortcut to switch to code view( without tree structure ) and not fullscreen?

There is a setting to go Zen without going full-screen, but no shortcut. Is that what you're looking for? If you want to provide more input, or have questions, could you open a new issue for it?

**Comment by jasonmelgoza** [comment]
:+1: cool!
