### ISSUE TITLE
This package added 276ms to startup time.

### ISSUE THREAD

**Issue by matmuchrapna** [defunkt/Zen#53]
it’s very huge delay for such tiny package, isn’t it?

**Comment by braver** [comment]
Zen should not affect startup time as it is not actually activated until you activate it. However, the first time Atom starts after an update to a package, it will compile and cache the coffee script, which will have quite an impact. Zen should not show up in Timecop at all after that first run.
If you reload atom, are you still seeing that impact on startup time?

**Comment by matmuchrapna** [comment]
Yeah, you are right! After reload zen added only 2ms to startup time.
