### ISSUE TITLE
Shows Fullscreen With No Text

### ISSUE THREAD

**Issue by shepting** [defunkt/Zen#56]
I use a secondary monitor with my MacBook lid closed. This is on Atom 194. It happens both with ctrl-command-z and ctrl-command-shift-f.

![screenshot 2015-04-22 15 55 11](https://cloud.githubusercontent.com/assets/48065/7287295/172d413e-e908-11e4-8aa5-395f6eb202b7.png)

**Comment by braver** [comment]
I've seen a similar issue in Atom installations without Zen installed. So it's not the package... might even be Electron related. Apparently Atom is a few versions behind, so let's hope it gets fixed. Nothing I can do though, so I'm closing this.
