### ISSUE TITLE
Font & Theme for Screenshots

### ISSUE THREAD

**Issue by shepting** [defunkt/Zen#57]
I was just wondering what font and theme is being used in the sample screenshots? It looks awesome.

**Comment by braver** [comment]
The theme is [Atom Dark](https://atom.io/themes/atom-dark-syntax) and I'm quite certain the font is [Inconsolata](http://programmingfonts.org/post/105953473597/inconsolata-inconsolata-is-my-first-serious)

**Comment by shepting** [comment]
Thanks!
