### ISSUE TITLE
Working in fullscreen mode, when you switch to Zen and back you are returned to a windowed view

### ISSUE THREAD

**Issue by adouglas** [defunkt/Zen#58]
I normaly work with Atom (currently 0.194.0) in fullscreen. Then when working on a file I can cmd-ctrl-z (or cmd-ctrl-shft-f) to Zen (currently 0.12.1).

However, when I exit Zen with cmd-ctrl-z (or cmd-ctrl-shft-f) I am returned to a windowed view of Atom. This is quite annoying and rather spoils the point of Zen for me.

**Comment by braver** [comment]
I have not been able to solve this reliably. What works for me is unchecking the "full screen" option for Zen, making the switch to full screen manual.

**Comment by braver** [comment]
No sightings in a while. I will close this, if it crops up again let me know.
