### ISSUE TITLE
Add option to deactivate text wrapping

### ISSUE THREAD

**Issue by rm-code** [defunkt/Zen#59]
Just a small suggestion: When you increase the width of Zen (to avoid text wrapping), the text starts at the left side of the screen. I think it would be nice to have an option to manually add some padding so that the text starts a bit more to the right.

**Comment by braver** [comment]
I don't think I completely understand? Could you perhaps illustrate what you want to accomplish?

**Comment by rm-code** [comment]
![screenshot 2015-04-28 10 43 28](https://cloud.githubusercontent.com/assets/11627131/7365822/ec2b2eb6-ed93-11e4-8cbf-887e2ed66b9c.png)
The top half shows how Zen currently looks for me. As you can see the text starts exactly at the screen's border. The bottom half shows how I'd like it to look - I'd love to have a setting which allows me to determine the distance between code and screenborder.

When I use the default "width" in Zen's settings, the panel is centered, but the text is wrapped automatically (maybe because I use a small 1280x720 screen):
![screenshot 2015-04-28 10 57 32](https://cloud.githubusercontent.com/assets/11627131/7366028/b15602b4-ed95-11e4-93c6-ab474b5d383a.png)

**Comment by braver** [comment]
Zen should be centered, even if you change the width. There have been reports of it aligning to the left, but I have been unable to reproduce it. Could you perhaps list the packages you've installed, and do you have any other customization going on? I'd love to get to the bottom of this.

**Comment by rm-code** [comment]
Sure thing - I use the following community packages:

- Zen (obviously)
- minimap
- language-lua

I'm using the Version 0.194.0 of Atom with all core packages enabled.

> Zen should be centered, even if you change the width. There have been reports of it aligning to the left, but I have been unable to reproduce it. 

I don't think that's the issue here. Maybe those people tried the same thing as me. The following screenshot shows how Zen look for me at width 80, 120, and 300.

![screenshot 2015-04-28 11 49 54](https://cloud.githubusercontent.com/assets/11627131/7367009/c3414cc0-ed9c-11e4-9de7-9db69b7fdcc2.png)

As you can see the first two options are in the center of the screen, whereas with a width of 300 it uses the whole screen's width (which makes perfect sense of course). At first I thought with a big width I could get rid of the text wrapping, but it looks like Zen just clamps it to the screen's width and still wraps long lines.

So maybe my suggestion should've been to add an option which allows to deactivate the text wrapping and instead adds horizontal scrolling.

**Comment by braver** [comment]
Oh right, that clarifies stuff a lot. :+1: 

> add an option which allows to deactivate the text wrapping and instead adds horizontal scrolling

Definitely all for this. I'm going to record it on the wish-list, I have some other priorities going on at the moment. If you're up for a PR, it should be as easy as skipping the part that toggles soft-wrapping if that option is set.

**Comment by rm-code** [comment]
Sure, I'll give it a try.
