### ISSUE TITLE
Zen not working?

### ISSUE THREAD

**Issue by kmisiunas** [defunkt/Zen#65]
Hi, 
great plugin - thanks for developing it. It seems to be struggling to work on Atom 0.198.0. Toggling between modes only activates full screen and that is it.

**Comment by kmisiunas** [comment]
OK. Restarting and waiting everything to load fixed the 'problem'. not sure about the cause now. Will try to reproduce it

**Comment by braver** [comment]
Would be really grateful if you could get a solid repro on this. I've seen some issues with Zen not centering, but I've only had it happen once and never again :disappointed:

**Comment by rm-code** [comment]
I had the same problem when I was working with my fork which is located in another directory. I'm wondering if this a problem with Atom itself. 

I had some strange issues with other plugins and themes which magically fixed themselves once I reloaded Atom (e.g. https://github.com/atom-minimap/minimap-git-diff/issues/8).

**Comment by braver** [comment]
Yes, I've had some really weird stuff happen that went away by themselves. Lots of under the hood changes the last few months. I'll close this until someone else runs into this again.
