### ISSUE TITLE
Different background color

### ISSUE THREAD

**Issue by sjaakvandenberg** [defunkt/Zen#66]
![screenshot_2015-05-23_12-12-59](https://cloud.githubusercontent.com/assets/10733082/7783513/67fb5e3e-0145-11e5-93a5-2ad52db27172.png)

The outer color in the screenshot is rgb(21, 23, 24). The inner color is rgb(16, 17, 18). The latter color is also the one that's used as background color when not using Zen.

Using Atom `0.200.0` with Zen `0.14.0` and the [Isotope](https://atom.io/themes/isotope-ui) UI theme and [Seti](https://atom.io/themes/seti-syntax) syntax theme on Arch Linux.

`~/.atom/packages/Zen/styles/zen.less` uses `@syntax-background-color`. 

![screenshot_2015-05-23_12-18-13](https://cloud.githubusercontent.com/assets/10733082/7783531/e0a75dec-0145-11e5-88a0-e96a5abce8a0.png)

`~/.atom/packages/seti-syntax/styles/syntax-variables.less` defines `@syntax-background-color` as: `@syntax-background-color: @code-background;`. It imports `colors.less`, which defines `@code-background` as: `@code-background: rgb(21,23,24); // editor background`.

The `~/.atom/packages/seti-syntax/styles/` directory however, has no `ui-variables.less` file.

Could this be causing a problem with Zen trying to import a background color from the syntax theme used? Is this even an issue with Zen at all, or rather with the Seti syntax theme?

**Comment by braver** [comment]
What happens is that Atom doesn't flush all cached stylesheets on a theme change. Packages that use syntax-variables in their stylesheets, like Zen does, will be not be updated if you switch from one theme to another. This is a known issue.
If you reload Atom, it will flush the caches and the colors should be correct. If they are not correct, it could be that the syntax theme is using the syntax-variables incorrectly. IIRC that used to be an issue with some of the more popular themes but I believe they have been corrected. Seti seems to work fine on my end.

**Comment by sjaakvandenberg** [comment]
I was running `atom-editor-bin` from the Arch User Repository. Reloading did not help, nor did restarting the editor, even after a reboot. I've uninstalled `atom-editor-bin` and switched to `atom-editor`, and that didn't help. Then I switched from the Isotope UI theme to Dark One, which did behave correctly, as does Spacegray Dark and Atom Dark.

**Comment by braver** [comment]
I'm not able to reproduce this with any syntax theme in any ui theme. However, the problem *has* to be with the editor background color definition in the syntax theme if it remains after a reload.
