### ISSUE TITLE
No padding at top of document

### ISSUE THREAD

**Issue by RaoOfPhysics** [defunkt/Zen#67]
When I activate Zen, the padding that used to appear at the top has not been present for a while now, and the top line of text sticks very close to the top of my screen:

![screen shot 2015-05-27 at 12 26 33](https://cloud.githubusercontent.com/assets/7623019/7834012/b2fd252e-046b-11e5-8830-6588d37f2398.png)

Is there any way I can fix this? I tried disabling all the installed extensions as well as most of the default ones without luck.

**Comment by rm-code** [comment]
Hello @RaoOfPhysics,

you can try adding this to your personal stylesheet:
```less
[data-zen="true"] {
  atom-text-editor:not(.mini) {
    padding-top: 20px; // Change this to your liking
  }
}
```

This works for me.

**Comment by braver** [comment]
Yes, that should work. The lack of padding at the top is by design.

**Comment by RaoOfPhysics** [comment]
@rm-code: That worked, many thanks! :)

@braver: Ah, I see. I thought it was a problem at my end because the screenshot in the README shows a padding (and indeed I happened to have had a padding for a while previously):

![](https://camo.githubusercontent.com/6dbae0fe77e4492d6aa9a2c93f39ca4db79c6271/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f322f323239303435352f63653939653937652d613031642d313165332d383830382d6562656334306539353962342e706e67)

A setting for padding in the GUI might be nice. :)

**Comment by rm-code** [comment]
I played around with a setting for the padding, but I didn't manage to make Zen restore the original "padding" options when exiting zen mode. Maybe @braver has more insight.

@RaoOfPhysics 
I use the "multiple" tabs option with [these custom style settings](https://gist.github.com/rm-code/c050440ef08c23016d25) in my personal style sheet:
![screenshot 2015-05-27 15 25 29](https://cloud.githubusercontent.com/assets/11627131/7836992/bd4497e2-0484-11e5-8277-3967afb0c9b6.png)
It produces a nice padding and makes the tabs unobtrusive. (It works for most of the themes I have installed).

**Comment by RaoOfPhysics** [comment]
Thanks, @rm-code, this is very helpful. :)

**Comment by jancborchardt** [comment]
@rm-code thanks for the code example! But it leads to the text cutting of at the top (more of margin than padding):
![capture du 2015-10-14 11-09-02](https://cloud.githubusercontent.com/assets/925062/10469737/2adf70ea-7264-11e5-9b62-fe0d5f5f97c8.png)
Is there another rule which will make it correctly scroll up further and visible?

@braver I’m not usually one to ask for settings (am a designer myself) but it’s very strange to have the text stick to the top. If it’s not going to be considered for the default style, a setting might be cool for this.

**Comment by braver** [comment]
What you're asking for, padding the top of the document so you can scroll it down from the top of the view, is as far as I know not possible. Everything you add at the top you lose at the bottom and several layers (highlights, gutter) need to be adjusted.
Zen used to have what your screenshot shows, but that just looks weird and tacky. I would love to have proper padding as a default, it's just that I don't know how to make it happen, and what your screenshot shows is just not acceptable as a compromise.

**Comment by dasilvacontin** [comment]
Fiddling a bit, I got a solution where you don't use `padding`, you use `margin`. It has no issues with scrolling. Con: you lose the editor's background color, and get the window's background color instead.

```scss
[data-zen=true] {
  atom-text-editor:not(.mini) {
    margin-top: 50px;
    margin-bottom: 50px;
    background: transparent;
  }
}
```

**Comment by jancborchardt** [comment]
@dasilvacontin I tried that before as well of course and it has the same issue with being cut off:
![capture du 2016-03-30 11-15-31](https://cloud.githubusercontent.com/assets/925062/14137609/cc20aab8-f668-11e5-9758-71f99f512d7e.png)

**Comment by dasilvacontin** [comment]
@jancborchardt Ah, yeah, it will _always_ have a margin... I'll let you know if I come up with something else.
