### ISSUE TITLE
Suggestion: Center current line vertically

### ISSUE THREAD

**Issue by uliska** [defunkt/Zen#70]
While writing a document I had an idea and would like to suggest this as an addition to Zen (if you think it's in line with Zen's spirit):

How about a mode where the line with the cursor in is always centered vertically on the screen?
That means when the cursor goes to a new line (by navigating, entering a line break or by soft wrapping) it actually stays at the same vertical position while the surrounding text scrolls correspondingly. This could even work when there's less than one "page" of text, so one would actually start writing at the center of the screen.

I didn't try this out but I can imagine it would add to the idea of "distraction free writing".

**Comment by braver** [comment]
That is a pretty awesome idea :+1: I'm not really up to writing something like that, but would welcome a PR to at least investigate it.

**Comment by uliska** [comment]
With "I didn't try this out" I didn't mean I didn't try out implementing it but "I don't have an editor with that capability". I'm also not up to writing this yet. Maybe I'll be in some time if it turns out that I'll get my feet wet with Atom programming, but I don't know. There's so much other stuff to be done ...

**Comment by uliska** [comment]
It might be nice to add to that the idea of a three-line "window" in the middle of the screen. This should be a visible (smoothly designed) box so the eye has something to stick to, and text above and below that box could (to a configurable extent) be blurred/greyed out or whatever, so the author can even more concentrate on the text that is currently being entered.

**Comment by braver** [comment]
Alright, I put this in the idea box. Would definitely like seeing a PR for this, or perhaps a separate package. But I'm not going to keep this issue around because I'd rather be honest about the fact that I don't see any priority for this and I don't have the time required to go anywhere with this idea.
