### ISSUE TITLE
Show word count when tree view is shown?

### ISSUE THREAD

**Issue by RaoOfPhysics** [defunkt/Zen#71]
Would it be possible to show the word count at the bottom right-hand corner even when the tree view is enabled? Currently, enabling tree view hides the word count.

**Comment by rm-code** [comment]
I am unable to reproduce this over here. For me the word count is still visible when I toggle the tree-view on.
![screenshot 2015-07-03 09 35 09](https://cloud.githubusercontent.com/assets/11627131/8494810/b72376e8-2168-11e5-9e86-7e6fb48e26e6.png)

@RaoOfPhysics What Zen-settings do you use?

**Comment by RaoOfPhysics** [comment]
@rm-code: Ah, of course. My tree view is on the right. Can you check if switching yours reproduces the issue? Thanks!

**Comment by rm-code** [comment]
@RaoOfPhysics Yes now I can reproduce it too.

**Comment by RaoOfPhysics** [comment]
@rm-code: Thanks for confirming! Please let me know if I can help with fixing this.

**Comment by braver** [comment]
https://github.com/defunkt/Zen/commit/24d52a7fb1ca01f9cbbe3c43a50e216bd3220890

The word count option will allow you to choose the position for the word-count (as well as hiding it). That should allow to you keep it in view if you open the tree-view or something else on the right.

**Comment by RaoOfPhysics** [comment]
@braver: Wonderful, many thanks for this! I would, of course, have preferred to have both word count and tree view displayed on the right, but this is a reasonable compromise. :)
