### ISSUE TITLE
If I have Soft Wrap turned on when I enter Zen mode, it shouldn't be turned off when I leave Zen mode.

### ISSUE THREAD

**Issue by qjones** [defunkt/Zen#75]
This happened because I turned on Zen's Soft Wrap setting which enables/disables soft wrapping when Zen is activated/deactivated. If Soft Wrap was enabled when I activate Zen mode, it should remain on when I disable Zen mode.

**Comment by rm-code** [comment]
@qjones Can you please try the pull request and see if that fixes your issue?

It was cause by my commit which added soft wrap options to Zen. It doesn't reset the values correctly.
