### ISSUE TITLE
Hyperfocus-writing feature?

### ISSUE THREAD

**Issue by TimDupont** [defunkt/Zen#79]
Is it possible to add a Hyperfocus-writing feature to Zen?
Limelight.vim[1] does this for vim/Goyo[2].

Best wishes,
Tim
- - -
[1] https://github.com/junegunn/limelight.vim
[2] https://github.com/junegunn/goyo.vim

**Comment by braver** [comment]
Atom doesn't offer anything that we could hook into for this easily. You might be able to work some magic with the bracket highlighting. 
In any case... It would have value outside Zen, so I encourage developing this as a separate package. Also, as it stands we might look into pull requests and bug reports, but the maintainers for this package don't have time to look into feature requests.
