### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by miguelcarax** [defunkt/Zen#81]
I go zen mode but i'm seeing line number anyways, i have read here that unchecking Shadow DOM it's solved, but that doesn't work. I have 0.16.2 versión.

**Comment by rm-code** [comment]
![screenshot 2015-09-10 23 33 58](https://cloud.githubusercontent.com/assets/11627131/9801624/7e9b934a-5814-11e5-9ce3-94d03efc45c4.png)

Hello! Is the gutter in your preferences?

**Comment by miguelcarax** [comment]
it is, checked or unchecked line number continous appearing

**Comment by rm-code** [comment]
Which theme are you using?

**Comment by miguelcarax** [comment]
Atom Material + Solarized Dark

**Comment by rm-code** [comment]
Ok strange ... I can't reproduce it over here at all. 

Are you using any other plugins? Might be worth trying to deactivate them.

**Comment by miguelcarax** [comment]
I'm not using nothing unusual...

I have right now: alignment, fonts, file-icons, linter, set-syntax, terminal-plus, tool-bar, tool-bar-almighty, clipboard-history.

**Comment by braver** [comment]
I can't reproduce it and I'm not going to hunt down incompatible packages by hand, so I simply don't have the time to investigate this. If there is a clear and particular case I'll look into it, but as it is I'm closing this one.
