### ISSUE TITLE
Integrates poorly with UI/Syntax Themes?

### ISSUE THREAD

**Issue by jasonkuhrt** [defunkt/Zen#83]
Using Nucleus Dark with varying Syntax Themes:

##### With Seti
![screen shot 2015-10-07 at 10 54 46 am](https://cloud.githubusercontent.com/assets/284476/10341216/dc591976-6ce1-11e5-8064-7e6a8b2024eb.png)

##### With Gruvbox
![screen shot 2015-10-07 at 10 55 20 am](https://cloud.githubusercontent.com/assets/284476/10341244/f26079bc-6ce1-11e5-9d55-79096e6a0217.png)

##### With Atom Dark Fusion
![screen shot 2015-10-07 at 10 55 57 am](https://cloud.githubusercontent.com/assets/284476/10341257/02e895d0-6ce2-11e5-936c-ecf542a30cf7.png)

etc.

Most Syntax themes work poorly besides Seti above.

Sorry if this is not an issue with Zen but the integration here is intimidating for an outsider: Atom UI theme, Atom Syntax Theme, Atom Zen Plugin.

**Comment by braver** [comment]
I'm guessing you're switching themes without reloading Atom in-between. Atom doesn't flush all stylesheets properly when you switch themes, so packages that depend on the `ui-variables` don't update their styles reliably. I bet if you use Atom Dark Fusion and reload Atom the problem disappears.

**Comment by jasonkuhrt** [comment]
@braver Yes! Maybe its worth explicitly stating this caveat in the README.
