### ISSUE TITLE
option to show current filename

### ISSUE THREAD

**Issue by mattsawyer77** [defunkt/Zen#84]
Just a suggestion, but would it be possible to add an option to show the filename in the footer? I like having tabs hidden (all the time, actually), but just a simple visual reminder of the buffer's filename would be nice.

**Comment by braver** [comment]
Not just with stylesheets, at least not without seriously hacky stuff with the statusbar. You could try something with your user stylesheet first?

**Comment by rm-code** [comment]
@mattsawyer77 

Add this to your user stylesheet:
```

[data-zen="true"] {
    .status-bar .file-info {
        position: fixed;
        bottom: 0;
        left: 0;
        right: auto;
        padding: 0 @component-padding;
        background: none;
        color: @syntax-text-color;
    }
}
```
It adds the path to the bottom left corner:
![screenshot 2015-12-19 16 17 57](https://cloud.githubusercontent.com/assets/11627131/11913679/36524d62-a66c-11e5-9585-5c9c15f4c8c6.png)

**Comment by braver** [comment]
I'm closing this as there seems to be a good user-space solution.
