### ISSUE TITLE
Adopt background colour

### ISSUE THREAD

**Issue by JonathanMH** [defunkt/Zen#86]
Hello,

I have been fiddling with themes a little recently, so I was wondering if it was possible to set the background colour from the syntax theme to "the thing around" the editor area in the shift+F11 full screen mode?

It's because I use a combination of seti-ui and mYnide and they don't have the same background colours, but it's only a bother in zen mode really.

**Comment by braver** [comment]
This already happens for themes that follow the conventions for the syntax-variables.less and and ui-variables.less files. In this case, I suspect mYnide is setting its background color in an unconventional way. There is no clean way to determine the actual rendered background color of the editor area. Instead, we rely on the styling conventions most themes follow. I don't see a clean way of supporting this theme combination on the package end, instead I suggest trying to get the themes to comply to conventions to make them compatible with this package (and possibly others).
