### ISSUE TITLE
Nuclide tree is not hiding

### ISSUE THREAD

**Issue by ColCh** [defunkt/Zen#87]
In [Nuclide](http://nuclide.io/), __tree-view__ is replaced with __nuclide-file-tree__.

This is typical picture when I go in Zen mode:

![image](https://cloud.githubusercontent.com/assets/599439/12649984/1e55ceaa-c5f2-11e5-82cd-01e7f47969f5.png)

(*File tree on the left side and Nuclide Toolbar on top* *)

There is some useful code in __nuclide-file-tree__:

This is interesting function for toggling visibility:
[toggleVisibility](https://github.com/facebooknuclideapm/nuclide-file-tree/blob/master/lib/FileTreeController.js#L264):
```js
function toggleVisibility() {
      var willBeVisible = !this._isVisible;
      this._setVisibility(willBeVisible);
      if (willBeVisible && this._revealActiveFilePending) {
        this.revealActiveFile();
        this._revealActiveFilePending = false;
      }
    }
```

And [this is binding](https://github.com/facebooknuclideapm/nuclide-file-tree/blob/master/lib/FileTreeController.js#L116) of this method to atom command __nuclide-file-tree:toggle__:
```
this._subscriptions.add(atom.commands.add('atom-workspace', {
      'nuclide-file-tree:reveal-active-file': this.revealActiveFile.bind(this),
      'nuclide-file-tree:toggle': this.toggleVisibility.bind(this),
      'nuclide-file-tree:toggle-focus': this.toggleTreeFocus.bind(this)
}));
```

Please tell me, which approach is better: Fixing __Zen__ package to work with __nuclide-file-tree__ or vice versa? I can't decide which package needs PR really.

------------------------------
PS:
* About top __Toolbar__ - I can hide it without trobles - I'm not using it actively. But __tree-view__ auto toggling is very sensible feature.

**Comment by braver** [comment]
I think it's better to make the change to Zen in this case. I'd welcome a PR!

**Comment by ColCh** [comment]
@braver Nice! I will prepare patch this night.
