### ISSUE TITLE
Zen mode doesn't display correctly

### ISSUE THREAD

**Issue by ianb** [defunkt/Zen#89]
Using Atom 1.5.3 and Zen Writer 0.16.4 the page displays like this for me:

![image](https://cloud.githubusercontent.com/assets/44390/13377621/d33e8bd2-dda7-11e5-9beb-18e48d01d546.png)

The reduced-width tab persists after I leave Zen mode.

**Comment by cortner** [comment]
Maybe a related problem: text doesn't flow the same way in zen mode and normal:

**Normal**
<img width="778" alt="screen shot 2016-06-03 at 09 22 55" src="https://cloud.githubusercontent.com/assets/7688515/15773095/f8082b06-296c-11e6-9448-bfd79c7242c4.png">

**Zen**
<img width="794" alt="screen shot 2016-06-03 at 09 22 50" src="https://cloud.githubusercontent.com/assets/7688515/15773090/f35e8348-296c-11e6-8da9-ffcb6ff823e6.png">

**Comment by braver** [comment]
I'm not experiencing any of this
