### ISSUE TITLE
Change font and font-size for Zen

### ISSUE THREAD

**Issue by rebrimhall** [defunkt/Zen#9]
It seems like it should be possible to change the font face and size for the editor in Zen using user styles but I can't seem to get it to work. Is this currently possible?

**Comment by linickx** [comment]
:+1:  for a settings option.

Note for other googlers; this is now:

```
[data-zen="true"] {
    atom-text-editor:not(.mini) {
        font-size: 24px;
    }
}
```

Well, it is for me :wink: 

Atom: 0.201.0 | Zen: 0.14.0

**Comment by braver** [comment]
Yes that would work. Settings options for packages can't change values in the stylesheets, they can only apply inline styles (or mess about with changing your actual config values). So using your personal stylesheet for this is actually preferable over all other options.
