### ISSUE TITLE
Scroll bar should not be moved away from window edge

### ISSUE THREAD

**Issue by z0u** [defunkt/Zen#95]
When in Zen mode, the scroll bar is moved to the edge of the text area. It would be better if it stayed at the edge of the window, to make it easier to click on according to [Fitt's Law](http://www.particletree.com/features/visualizing-fittss-law/).

One possible way to implement this would be to remove the right-hand margin entirely (for LTR text with soft-wrapping disabled, at least).

**Comment by shawnkirsch** [comment]
agreed.  this is really jarring

**Comment by braver** [comment]
Sadly, with the way Atom's layout is structured internally, this is extremely hard to do.
