### ISSUE TITLE
Focus mode?

### ISSUE THREAD

**Issue by orschiro** [defunkt/Zen#98]
Dear @defunkt,

Thank you very much for your great plugin!

I have one question:

What do you think of a focus mode such as shown by the below example?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18231263/2bd22220-72b5-11e6-8adb-8477c47f9d12.png)

**Comment by braver** [comment]
@orschiro As you'll have noticed maintenance on this package isn't very active. I'm also definitely not looking to expanding the scope of this package, any additional features not directly related to going full-screen and removing elements from the view are better handled by other packages.

**Comment by orschiro** [comment]
Alright, thanks for your response though!
