### ISSUE TITLE
Returning from zen mode to normal mode moves Atom from fullscreen to windowed mode on osx.

### ISSUE THREAD

**Issue by mmurto** [defunkt/Zen#99]
On osx 10.11.6 beta. 

What happens:
Normal mode (fullscreen) -> Zen (fullscreen) -> Normal mode (windowed). 

Should probably be:
Normal mode (fullscreen) -> Zen (fullscreen) -> Normal mode (fullscreen).

**Comment by xh3b4sd** [comment]
Happened also to me. This behaviour is more annoying than any disturbances in the editor itself. With this bug the package is kind of useless to me. Can somebody fix this?

**Comment by baelter** [comment]
Just disable fullscreen in the packages setting and zen will leave your fullscreen setting alone. If windowed, zen will be windowed and if fullscreen, zen will be fullscreen.

**Comment by braver** [comment]
@baelter is correct here, that's the way to solve this.
